export interface User {
firstname:string,
lastname:string,
username:string,
email:string,
password:string,
country:string,
phoneNumber:string,
gender:string,
title:string,
summary:string,
moneyAccount:number,
HourRate:number,
categoryName:string,
}
